#--- Variables --------------------------------------------------------------------------------------------
PROJECT_NAME         = Flame
PROJECT_VERSION      = 1.0.0
PROJECT_DESCRIPTION  = Symmetric traveling salesman problem solver
PROJECT_AUTHORS      = Nicolas Lermé
PROJECT_LICENSE      = LGPL-v3
PROJECT_LAST_RELEASE = `date`
